### ISSUE TITLE
Add 'validate_vars' to ciscops.mdd.validate

### ISSUE THREAD

**Issue by stevenca** [model-driven-devops/mdd#61]
Need to be able to specify the following to mimic the same functionality in ciscops.mdd.check:
```
---
mdd_tags:
  - all
mdd_schemas:
  - name: banner
    file: 'local/banner.schema.yml'
  - name: dns
    file: 'local/dns.schema.yml'
    validate_vars:
        dns_servers:
           - 8.8.8.8
           - 8.8.4.4
```
